name: openssl-feed

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  pip-check:
    runs-on: ubuntu-latest
    steps:
      - uses: guilhem/rss-issues-action@986ed8da58498e128286eee9d9a1ba2e0a3b7902 # v0.5.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          feed: https://github.com/openssl/openssl/releases.atom
          prefix: "New OpenSSL release:"
          lastTime: "24h"
          labels: "openssl-version"
